version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: to-do-list-api
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
